### ISSUE TITLE
Make snapshots work again

### ISSUE THREAD

**Issue by kcrisman** [sagemath/sagenb#236]
Currently, all snapshots made (exactly when they are made is a bit of a mystery, but see sagenb/flask_version/worksheet.py for the `@worksheet_command`s) are IDENTICAL to the last version of the worksheet.  This is completely useless, and actually worse than useless because it is misleading to users.  Many have complained.  This happened about the time that autosaves were greatly reduced, but no one has yet found the source of this.  Maybe now is the time.

**Comment by novoselt** [comment]
I have a question - how the snapshots are **supposed** to work? On my "work" server I observe the following: with 1 minute autosave interval there are no revisions. When I press "Save" there are still no revisions. When I press "Save & Quit", then open worksheet again and go to revisions, there are some which seem to coincide with me pressing either of two saving buttons. Is this expected behaviour? Any chance of writing some explanation of how things work/should work on the top of revisions page similar to how it is done for data, e.g. I create a file and see instructions

Access 234 in this worksheet by typing DATA+'234'. Here DATA is a special variable that gives the exact path to all data files uploaded to this worksheet.

**Comment by kcrisman** [comment]
> Any chance of writing some explanation of how things work/should work on the top of revisions page similar to how it is done for data, 

Open a ticket here and I might be able to do this.  "Save" should have worked properly, I believe.  By the way, this is somewhat separate from the autosave, which is still apparently more or less broken.

**Comment by schymans** [comment]
I got here from http://trac.sagemath.org/ticket/8776 and in both places the situation seems to be fixed, but unfortunately, in Sage 6.6, I still do not see the snapshots. Do I need to update something separately? Thanks for your work on this!

**Comment by kcrisman** [comment]
Can you be more specific as to what isn't working?  You do need to use the History tab, if memory serves.  Also, it only takes a snapshot when you explicitly save (currently).

**Comment by schymans** [comment]
Strange, if I click on "Save" or "Save and quit" now, I see a new revision when I then re-open and click on "Revisions". However, most of my worksheets have no revisions at all in the revision history. I'll keep in mind to save more often and then I'll watch if the revisions actually survive rebooting. Are they stored in the worksheet folder? Thanks for the quick reply!

**Comment by kcrisman** [comment]
Interesting.  I can't say for sure exactly why you are seeing that behavior; yes, they should be in the given folder, if I recall correctly (which I may not).

**Comment by schymans** [comment]
Thanks, I found them. Each worksheet in sage_notebook.sagenb/home/admin/ has a subfolder snapshots if any snapshots were created. I can now see how a new .bz2 file is added to the folder when I click on save. However, for some reason the new snapshot does not show in the list when I then click on "Revisions" in the browser. Perhaps the contents of the snapshots directory are not refreshed frequently?

**Comment by kcrisman** [comment]
That is more or less correct, you have to reload the page or reset the cache or something - I came across this in testing.  I usually "Save and Quit" and then restart.  Good luck!
