### ISSUE TITLE
Version 11.2 breaks sage parsing...

### ISSUE THREAD

**Issue by gutow** [sagemath/sagenb#335]
If I use the 11.0 version of the notebook with sage 6.4 and enter things like `x^2` into a compute cell it works fine.  If I switch to version 11.2 I get the error message telling me that `^` is xor and that I should use `**`.  I just copied the master branch 10 minutes ago.  This is shall we say baaaad!  I tried poking around a little but cannot figure out what is wrong.  It still looks like the execute call is being passed normally to the sage back end...could it have something to do with moving the temporary files?

**Comment by gutow** [comment]
Just rolled it back to first 11.1 version.  Parsing works fine in that.  I will try the bisect command, but am not very good with it and report back.

**Comment by kcrisman** [comment]
I'm really skeptical of this, but I'll check it out... I cannot reproduce this.  I agree it would be bad.
When you say 'moving the temporary files' do you mean #331 ?

**Comment by kcrisman** [comment]
Is it conceivable you have the wrong system chosen for evaluation (such as python, not sage)?
![screen shot 2015-01-10 at 10 23 17 pm](https://cloud.githubusercontent.com/assets/1775728/5694200/c8889c82-9915-11e4-9f52-cca048c90a2f.png)

**Comment by gutow** [comment]
Bisect is cool.  I checked the menu. The offending commit is:
commit 29d7044021328743fb07c8504c44e1379b939e70
Author: Jeroen Demeyer <jdemeyer@cage.ugent.be>
Date:   Sat Dec 6 21:57:19 2014 +0100

    Fix various sage import locations

:040000 040000 8321de45504c767e8cca5b7b87811fdce8bd465a 61f30a936c85c0a0ed62eadc9f4d6cd0174dd088 M	sagenb

I haven't got time to check now, but I'm assuming part of the parsing got left out.

**Comment by kcrisman** [comment]
You need to use this with the correct version of Sage, @gutow.  Notice that the changes refer to `sage.repl.preparse`.  [The current master](http://git.sagemath.org/sage.git/tree/src/sage/repl) does not have this, but Jeroen (I think) moved this and [the current develop](http://git.sagemath.org/sage.git/tree/src/sage/repl?h=develop) has it.  You are right that this is exactly what should happen otherwise, though I'm surprised that it just doesn't crash Sage... there should be some errors in your sagenb log about missing imports.

**Comment by kcrisman** [comment]
(By the way, I'd be open to any suggestion about how to match up Sage and sagenb versions better, but I have no idea how to enforce this.  Note that 0.11.2 isn't even in an officially released *beta* of Sage, presumably will be in the next beta.)

**Comment by gutow** [comment]
This is a problem.  I'm just trying to get a notebook that works properly with proxying under the present sage release.  I guess I will have to do some cherry picking...

**Comment by kcrisman** [comment]
> I guess I will have to do some cherry picking...

Yes, unfortunately.  Hopefully you can "just rebase" your changes; this is what @migeruhito does with some of his custom changes, I believe.  I'm simply not going to be in a position to review #328 for quite some time, even though the changes are all similar to each other, I just have to really wrap my head around it.  Such changes usually cause other bugs, just the name of the game.

**Comment by gutow** [comment]
Two thoughts on versioning:

1. I suggest a scheme such as sagenb-X.Y.Z-for_sage-Q.R.M or sagenb-X.Y.Z-sage-Q.R.M.
1. The master branch of sagenb should probably never be for a beta of sage.  By anology with what we do with Jmol, we never put changes into the stable release that depend on unreleased browser or javascript features.  They stay in the development branch until the browsers release them.

**Comment by kcrisman** [comment]
1. is too unwieldy, I think.  2. has some promise but requires more involvement than just me :smiley:  That said, I think that the way Sage development works it should be okay, because sagenb 0.11.2 was merged after the changes in Sage in question; it isn't really a true "upstream" project, even though this was the original intent.
