### ISSUE TITLE
Sage Dependency

### ISSUE THREAD

**Issue by alfredoport** [sagemath/sagenb#94]
Currently when trying to run the notebook without Sage, one gets the following dependency error:

File "sagenb/sagenb/notebook/interact.py", line 158, in <module>
 from sage.misc.cachefunc import cached_method
ImportError: No module named sage.misc.cachefunc

**Comment by kcrisman** [comment]
I'm gonna close this as "wontfix" because of the current status where sagenb is in maintenance mode, and where eventually (someday) would be deprecated.  That doesn't mean someone couldn't do this, but for now it's not on the radar, quite the reverse (there has been talk about bringing it back in Sage, though that probably also isn't worth the effort).
